# Site
title:          francesco la vella
bio:            "pensieri sparsi"
description:    "su di me e altre storie"
picture:        "assets/img/profile.png"
locale:         it_IT

url: "https://www.francescolavella.it" # senza slash finale!
baseurl: ""    # attenzione allo slash iniziale

# Jekyll
permalink:      /:title/
markdown:       kramdown
highlighter:    rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed

# Social
twitter: francescolv
facebook: francescolv
github: francescolv
linkedin: francescolv
instagram: francescolv

# Comments
disqus_shortname: francescolavella

plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-youtube
  - jekyll-analytics
  - jekyll-seo-tag

jekyll-mentions:
  base_url: https://github.com

# Exclude list
exclude:
  - README.md
  - node_modules
  - vendor
  - src
  - CNAME
  - LICENSE
  - Rakefile
  