# Site
title:          francesco la vella
bio:            "pensieri sparsi"
description:    "su di me e altre storie"
picture:        "assets/img/profile.png"
locale:         it_IT

url: "https://francescolv.github.io"
baseurl: "/francescolavella.it"   # attenzione allo slash iniziale

# Jekyll
permalink:      /:title/
markdown:       kramdown
highlighter:    rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed

# Social
twitter: francescolv
facebook: francescolv
github: francescolv
linkedin: francescolv
instagram: francescolv
#email:
#google:
  #plus: #username
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
#xing: username
#lastfm: username
#tumblr: username
#pinterest: username
#foursquare: username
#steam: username
#dribbble: username
#youtube: username
#soundcloud: username
#weibo: username
#flickr: username
#codepen: username

# Paginate
# if you don"t need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

#Google Analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-134462764-1      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

# Comments
disqus_shortname: francescolavella

plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  #- jekyll-paginate
  - jekyll-gallery-generator
  - jekyll-youtube
  - jekyll-analytics
  - jekyll-seo-tag

jekyll-mentions:
  base_url: https://github.com

#Gallery
gallery:
  dir: photos               # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Photos"           # Title for gallery index page
  title_prefix: "Photos:"  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
  
  # The following options are for individual galleries.
  galleries:
    serra:
      best_image: serrahome.png  # The image to show on the gallery index page. Defaults to the last image.
      name: "Serra"
      #hidden: true          # Don't show this gallery on the index page. People must guess the URL.
      #sort_reverse: true    # Reverse sort images in gallery.
      #info:
      #  desc: "Gallery Description" # Info fields can be used in custom templates.

# Exclude list
#exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]