# Override solo per il build su CI (GitHub Actions)
url: "https://francescolv.github.io"
baseurl: ""         # user page = vuoto
lsi: false
incremental: false
safe: false         # compiliamo noi, quindi ok anche con plugin non whitelisted da Pages classico
future: false
