# Override solo per il build su CI (GitHub Actions)
url: "https://www.francescolavella.it"  # user page = dominio personalizzato
baseurl: ""         # user page = vuoto
lsi: false
incremental: false
safe: false         # compiliamo noi, quindi ok anche con plugin non whitelisted da Pages classico
future: false
